const MONGODB_URL = process.env.MONGODB_URL;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const CALLBACK_URL = process.env.CALLBACK_URL;
module.exports = {
  MONGODB_URL,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  CALLBACK_URL
};
